{{ config(
    materialized='table'
) }}


WITH Aggregated_Quarterly_Metrics AS (
    SELECT
        SK_COUNTRY_PERIOD,
        COUNTRY,
        QUARTERLY_PERIODS,
        SUM(CASE WHEN METRIC_TYPE = 'Satisfaction' THEN WEIGHT_PER_PERSON ELSE 0 END) AS TOTAL_SATISFACTION_WEIGHT_X1, 
        SUM(CASE WHEN METRIC_TYPE = 'Dissatisfaction' THEN WEIGHT_PER_PERSON ELSE 0 END) AS TOTAL_DISSATISFACTION_WEIGHT_X1, 
        COUNT(DISTINCT CASE WHEN METRIC_TYPE = 'Satisfaction' THEN UNIQUE_ID ELSE NULL END) AS TOTAL_SATISFACTION_SAMPLE,
        COUNT(DISTINCT CASE WHEN METRIC_TYPE = 'Dissatisfaction' THEN UNIQUE_ID ELSE NULL END) AS TOTAL_DISSATISFACTION_SAMPLE,
    FROM {{ ref('int_satisfaction_data') }}
    GROUP BY COUNTRY, QUARTERLY_PERIODS, SK_COUNTRY_PERIOD
),

Aggregated_Features_Metrics AS (
    SELECT
        SK_COUNTRY_PERIOD,
        COUNTRY,
        QUARTERLY_PERIODS,
        FEATURE,
        RESTAURANT_BRAND,
        BOOKING_CHANNEL,
        AGE_BREAKS,
        ORDER_TYPE,
        CITY,
        RESERVATION_TYPE,
        SUM(CASE WHEN METRIC_TYPE = 'Satisfaction' THEN SATISFACTION_WEIGHT ELSE 0 END) AS SATISFACTION_WEIGHT_X1, 
        SUM(CASE WHEN METRIC_TYPE = 'Dissatisfaction' THEN DISSATISFACTION_WEIGHT ELSE 0 END) AS DISSATISFACTION_WEIGHT_X1, 
    FROM {{ ref('int_satisfaction_data') }}
    GROUP BY COUNTRY, QUARTERLY_PERIODS, FEATURE, RESTAURANT_BRAND, BOOKING_CHANNEL, AGE_BREAKS, ORDER_TYPE, CITY, RESERVATION_TYPE,SK_COUNTRY_PERIOD
),

Satisfaction_Drivers AS (
    SELECT
        af.SK_COUNTRY_PERIOD,
        af.COUNTRY,
        af.QUARTERLY_PERIODS,
        af.FEATURE AS DRIVERS_OF_SATISFACTION_X1,
        af.RESTAURANT_BRAND,
        af.BOOKING_CHANNEL,
        af.AGE_BREAKS,
        af.ORDER_TYPE,
        af.CITY,
        af.RESERVATION_TYPE,

        aq.TOTAL_SATISFACTION_SAMPLE + aq.TOTAL_DISSATISFACTION_SAMPLE AS SAMPLE_SIZE,
        ROUND((af.SATISFACTION_WEIGHT_X1 / aq.TOTAL_SATISFACTION_WEIGHT_X1) * 100, 2) AS SATISFACTION_PERCENTAGE_Y1,
        ROUND((af.DISSATISFACTION_WEIGHT_X1 / aq.TOTAL_DISSATISFACTION_WEIGHT_X1) * 100, 2) AS DISSATISFACTION_PERCENTAGE_Y1,
        ROUND((af.SATISFACTION_WEIGHT_X1 / aq.TOTAL_SATISFACTION_WEIGHT_X1) * 100, 2) - ROUND((af.DISSATISFACTION_WEIGHT_X1 / aq.TOTAL_DISSATISFACTION_WEIGHT_X1) * 100, 2) AS NET_SATISFACTION_PERCENTAGE_Y1
    FROM Aggregated_Features_Metrics af
    JOIN Aggregated_Quarterly_Metrics aq 
        ON af.SK_COUNTRY_PERIOD = aq.SK_COUNTRY_PERIOD
)

SELECT
    SK_COUNTRY_PERIOD,
    COUNTRY,
    QUARTERLY_PERIODS,
    MAKE_DATE(left(QUARTERLY_PERIODS,4)::integer, (right(QUARTERLY_PERIODS,1)::integer - 1) * 3 + 1, 1) AS QUARTERLY_PERIODS_START_DATE,

    RESTAURANT_BRAND,
    BOOKING_CHANNEL,
    AGE_BREAKS,
    ORDER_TYPE,
    CITY,
    RESERVATION_TYPE,

    SAMPLE_SIZE,
    DRIVERS_OF_SATISFACTION_X1,
    NET_SATISFACTION_PERCENTAGE_Y1
FROM Satisfaction_Drivers